name: tn_edii
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  animated_visibility: ^0.0.4
  cache_manager: ^1.0.0+4
  cached_network_image: ^3.3.1
  calendar_view: ^1.2.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.8
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.0
  flutter_secure_storage: ^9.2.2
  fluttertoast: ^8.2.6
  go_router: ^14.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  linear_progress_bar: ^1.1.2
  location: ^7.0.0
  logger: ^2.4.0
  mime: ^1.0.5
  ntp: ^2.0.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  pinput: ^5.0.0
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.2
  # readmore: ^3.0.0
  readmore: ^3.0.0
  share_plus: ^10.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  weather_animation: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
  # Icons
    - assets/icons/
    - assets/icons/home_icons/

  # Images
    - assets/images/
    - assets/images/resources_images/
    - assets/images/onboarding_images/
    - assets/images/banner_images/
    - assets/images/experts_images/
   

  ## Fonts
  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Mulish-Black.ttf
          weight: 900